[package]
name = "kernel"
version = "0.11.0"
authors = ["Maxim Sokhatskyi <maxim@synrc.com>"]
license = "MIT"
repository = "https://github.com/AlgoTradingHub/kernel"
homepage = "https://github.com/AlgoTradingHub/kernel"
documentation = "http://5ht.co/kernel.htm"
description = """
Abstract Reactive Streams
"""
build = "build.rs"

[[bin]]
name = "fix"
path = "src/apps/protocols/fix.rs"

[[bin]]
name = "sh"
path = "src/apps/sh.rs"

[[bin]]
name = "sup"
path = "src/apps/sup.rs"

[[bin]]
name = "top"
path = "src/apps/top.rs"

[[bin]]
name = "mio"
path = "src/apps/mio.rs"

[[bin]]
name = "client"
path = "src/apps/client.rs"

[[bin]]
name = "server"
path = "src/apps/server.rs"

[[bin]]
name = "console"
path = "src/apps/console.rs"

[dependencies]
net2         = "0.2.19"
log          = "0.3"
rand         = "0.3.14"
bitflags     = "0.4"
num          = "0.1.36"
byteorder    = "0.5.3"
hwloc        = "0.3.0"
lalrpop-util = "0.12.0"
num_cpus     = "1.0"
deque        = "0.3.1"

[target.'cfg(unix)'.dependencies]
nix          = "0.6.0"
libc         = "0.2.14"

[build-dependencies]
lalrpop = "0.12.0"
